name = "vhlink"
type = "javascript"
account_id = "39a76d640a29996bffbd58c36a537c2b"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "154095d4873b4fcc99cb54ae07a23037", preview_id = "154095d4873b4fcc99cb54ae07a23037" }
]
